Repository hmcts/fact-api, pull requests merged in 2021-05, with the labels that each got.

#306 FACT-411 - Added batch of Breathing Space emails into DB
  src/main/resources/db/migration/V091__breathing_space_emails.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-306

#295 FACT-456 - Implement LaunchDarkly / Feature Flag support
  build.gradle
  charts/fact-api/Chart.yaml
  charts/fact-api/values.aat.template.yaml
  charts/fact-api/values.yaml
  infrastructure/main.tf
  src/main/java/uk/gov/hmcts/dts/fact/controllers/FeatureFlagController.java
  src/main/java/uk/gov/hmcts/dts/fact/launchdarkly/LaunchDarklyClient.java
  src/main/java/uk/gov/hmcts/dts/fact/launchdarkly/LaunchDarklyClientFactory.java
  src/main/resources/application.yaml
  src/main/resources/bootstrap.yaml
  src/test/java/uk/gov/hmcts/dts/fact/launchdarkly/LaunchDarklyClientFactoryTest.java
  src/test/java/uk/gov/hmcts/dts/fact/launchdarkly/LaunchDarklyClientTest.java
Labels: ns:fact, prd:fact, rel:fact-api-pr-295

#314 FACT-492 - Batch court changes 9
  src/main/resources/db/migration/V092__batch_changes_9.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-314

#316 FACT-493 - Return in person court information from admin general info endpoint
  src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtGeneralInfoEndpointTest.java
  src/main/java/uk/gov/hmcts/dts/fact/model/admin/CourtGeneralInfo.java
  src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtGeneralInfoControllerTest.java
  src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtGeneralInfoServiceTest.java
Labels: ns:fact, prd:fact, rel:fact-api-pr-316

#319 FACT-505 - Batch court changes 11
  src/main/resources/db/migration/V094__batch_court_changes_11.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-319

#321 FACT-74 & FACT-95 - Add email and phone number endpoints for the admin portal - take 3
  src/main/resources/db/migration/V095__admin_email_categorisation.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-321

#322 FACT-74 & FACT-95 - Fixed sonarqube complaint
  src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtTypesService.java
Labels: ns:fact, prd:fact, rel:fact-api-pr-322

#324 FACT-74 - Reassign 'Criminal' e-mail and contact types to 'Crown court' or 'Magistrates court'
  README.md
  src/main/resources/db/migration/V097__reassign_criminal_email_and_contact_types.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-324

#325 C100-patch - Added in cci_code field to deprecated court object.
  src/main/java/uk/gov/hmcts/dts/fact/model/deprecated/OldCourt.java
Labels: ns:fact, prd:fact, rel:fact-api-pr-325

#329 FACT-513 - Court batch changes 12
  src/main/resources/db/migration/V098__batch_court_changes_12.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-329

#326 FACT-74 & FACT-95 - Populate the explanation fields of email and contact
  README.md
  src/main/resources/db/migration/V099__update_explanation_for_crown_court_listings.sql
  src/main/resources/db/migration/V100__populate_email_and_contact_explanations.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-326

#333 Fact 525 - New endpoint for searching by prefix and active boolean
  src/functionalTest/java/uk/gov/hmcts/dts/fact/CourtsEndpointTest.java
  src/integrationTest/java/uk/gov/hmcts/dts/fact/repositories/CourtRepositoryTest.java
  src/main/java/uk/gov/hmcts/dts/fact/controllers/CourtsController.java
  src/main/java/uk/gov/hmcts/dts/fact/repositories/CourtRepository.java
  src/main/java/uk/gov/hmcts/dts/fact/services/CourtService.java
  src/test/java/uk/gov/hmcts/dts/fact/controllers/CourtsControllerTest.java
  src/test/java/uk/gov/hmcts/dts/fact/services/CourtServiceTest.java
Labels: ns:fact, prd:fact, rel:fact-api-pr-333

#330 FACT-95 - Fix issue where the phone numbers sometimes not returned in expected order
  src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtContactEndpointTest.java
  src/integrationTest/java/uk/gov/hmcts/dts/fact/repositories/CourtRepositoryTest.java
  src/main/java/uk/gov/hmcts/dts/fact/entity/Contact.java
  src/main/java/uk/gov/hmcts/dts/fact/entity/Court.java
  src/main/java/uk/gov/hmcts/dts/fact/entity/CourtContact.java
  src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtContactService.java
  src/main/resources/db/migration/V101__move_contact_sort_order_column.sql
  src/test/java/uk/gov/hmcts/dts/fact/entity/ContactTest.java
  src/test/java/uk/gov/hmcts/dts/fact/model/CourtTest.java
  src/test/java/uk/gov/hmcts/dts/fact/model/admin/ContactTest.java
  src/test/java/uk/gov/hmcts/dts/fact/model/admin/CourtTest.java
  src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtContactServiceTest.java
Labels: ns:fact, prd:fact, rel:fact-api-pr-330

#336 FACT-529 - Filter out DX number from admin portal phone number list ad keep DX number after admin updating phone numbers
  README.md
  src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtContactEndpointTest.java
  src/integrationTest/java/uk/gov/hmcts/dts/fact/repositories/ContactTypeRepositoryTest.java
  src/main/java/uk/gov/hmcts/dts/fact/entity/Contact.java
  src/main/java/uk/gov/hmcts/dts/fact/model/Contact.java
  src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtContactService.java
  src/main/resources/db/migration/V102__remove_DX_from_contact_type_list.sql
  src/test/java/uk/gov/hmcts/dts/fact/model/ContactTest.java
  src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtContactServiceTest.java
Labels: ns:fact, prd:fact, rel:fact-api-pr-336

#337 FACT-529 - Update readme file to kick off Jenkins build again
  README.md
Labels: ns:fact, prd:fact, rel:fact-api-pr-337

#332 FACT-528 - Update timestamp column on the search_court table when court content is updated
  src/integrationTest/java/uk/gov/hmcts/dts/fact/repositories/CourtRepositoryTest.java
  src/main/java/uk/gov/hmcts/dts/fact/entity/Court.java
  src/main/java/uk/gov/hmcts/dts/fact/entity/CourtContact.java
  src/main/java/uk/gov/hmcts/dts/fact/entity/CourtEmail.java
  src/main/java/uk/gov/hmcts/dts/fact/entity/CourtOpeningTime.java
Labels: ns:fact, prd:fact, rel:fact-api-pr-332

#338 FACT-536 - Court batch changes 13
  src/main/resources/db/migration/V103__batch_court_changes_13.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-338

#339 FACT-525 - Find court by prefix using name rather than slug
  src/integrationTest/java/uk/gov/hmcts/dts/fact/repositories/CourtRepositoryTest.java
  src/main/java/uk/gov/hmcts/dts/fact/repositories/CourtRepository.java
  src/main/java/uk/gov/hmcts/dts/fact/services/CourtService.java
  src/test/java/uk/gov/hmcts/dts/fact/services/CourtServiceTest.java
Labels: ns:fact, prd:fact, rel:fact-api-pr-339

#343 CVE-2021-22112-Patch - Updated SpringBoot to 2.3.10.RELEASE
  build.gradle
Labels: ns:fact, prd:fact, rel:fact-api-pr-343

#342 FACT-542 - Fixed duplicate number on West Yorkshire Enforcement Office
  src/main/resources/db/migration/V104__W_Yorkshire_Enforcement_Office.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-342

#345 FACT-549 - Small content update for Newcastle upon Tyne Crown Court and Magistrates Court
  src/main/resources/db/migration/V105__newcastle_crown_magistrates_court_update.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-345
