Repository hmcts/fact-api, pull requests merged in 2021-04, with the labels that each got.

#258 FACT-361 - Corrected some welsh language translations in database
  src/main/resources/db/migration/V075__update_welsh_translation_to_facility_and_service_type.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-258

#261 trigger build Update README.md
  README.md
Labels: ns:fact, prd:fact, rel:fact-api-pr-261

#242 Autoscaling - bump chart
  charts/fact-api/Chart.yaml
  charts/fact-api/values.yaml
Labels: ns:fact, prd:fact, rel:fact-api-pr-242

#262 FACT-386 - Fixed Northampton postcode issue due to local authority mismatch between Mapit and FaCT database
  src/main/java/uk/gov/hmcts/dts/fact/services/CourtService.java
  src/test/java/uk/gov/hmcts/dts/fact/services/CourtServiceTest.java
Labels: ns:fact, prd:fact, rel:fact-api-pr-262

#263 FACT-383 - Flyway transformation for court data change request batch 1
  src/main/resources/db/migration/V076__batch_court_changes_1.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-263

#265 FACT-392 - Update Bristol and Yeovil courts opening hours
  src/main/resources/db/migration/V077__update_bristol_and_Yeovil_courts_opening_hours.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-265

#266 FACT-394 - Court content update for Bath, West Hampshire, Southampton, Exeter and Bournemouth courts
  README.md
  src/main/resources/db/migration/V078__varioius_court_details_update.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-266

#267 FACT-398 - Update Poole Magistrates' court opening hour
  src/main/resources/db/migration/V079__update_Poole_court_opening_hours.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-267

#268 FACT-393 - Update building facilities content for Southampton, Weymouth and Bournemouth Combined courts
  src/main/resources/db/migration/V080__varioius_court_details_update.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-268

#269 Bump base java chart version Update Chart.yaml
  charts/fact-api/Chart.yaml
Labels: ns:fact, prd:fact, rel:fact-api-pr-269

#277 FaCT - Batch changes for court data
  src/main/resources/db/migration/V081__batch_court_changes_3.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-277

#270 FACT-408 - Add new admin endpoints for getting and updating court opening times
  src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCommon.java
  src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtOpeningTimeEndpointTest.java
  src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtsEndpointTest.java
  src/main/java/uk/gov/hmcts/dts/fact/controllers/CourtsController.java
  src/main/java/uk/gov/hmcts/dts/fact/controllers/SearchController.java
  src/main/java/uk/gov/hmcts/dts/fact/controllers/ServiceAreasController.java
  src/main/java/uk/gov/hmcts/dts/fact/controllers/ServicesController.java
  src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtOpeningTimesController.java
  src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtsController.java
  src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminRole.java
  src/main/java/uk/gov/hmcts/dts/fact/entity/CourtOpeningTime.java
  src/main/java/uk/gov/hmcts/dts/fact/exception/GlobalControllerExceptionHandler.java
  src/main/java/uk/gov/hmcts/dts/fact/model/OpeningTime.java
  src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtOpeningTimeService.java
  src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminService.java
  src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtOpeningTimesControllerTest.java
  src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtsControllerTest.java
  src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtOpeningTimeServiceTest.java
  src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminServiceTest.java
  src/test/resources/opening-times.json
Labels: ns:fact, prd:fact, rel:fact-api-pr-270

#280 FACT-432 - Court Batch Changes 4
  README.md
  src/main/resources/db/migration/V082__batch_court_changes_4.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-280

#281 FACT-436 - Court data changes batch 5
  src/main/resources/db/migration/V083__batch_court_changes_5.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-281

#283 FACT-448 - Patch for CVE-2021-29425
  build.gradle
Labels: ns:fact, prd:fact, rel:fact-api-pr-283

#285 FACT-451 - Court data changes batch 6
  README.md
  src/main/resources/db/migration/V084__batch_court_changes_6.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-285

#284 FACT-407 - Add new API endpoints for admin opening times
  src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCommon.java
  src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtOpeningTimeEndpointTest.java
  src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtsEndpointTest.java
  src/main/java/uk/gov/hmcts/dts/fact/controllers/CourtsController.java
  src/main/java/uk/gov/hmcts/dts/fact/controllers/SearchController.java
  src/main/java/uk/gov/hmcts/dts/fact/controllers/ServiceAreasController.java
  src/main/java/uk/gov/hmcts/dts/fact/controllers/ServicesController.java
  src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtOpeningTimesController.java
  src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtsController.java
  src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminRole.java
  src/main/java/uk/gov/hmcts/dts/fact/entity/CourtOpeningTime.java
  src/main/java/uk/gov/hmcts/dts/fact/exception/GlobalControllerExceptionHandler.java
  src/main/java/uk/gov/hmcts/dts/fact/model/OpeningTime.java
  src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtOpeningTimeService.java
  src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminService.java
  src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtOpeningTimesControllerTest.java
  src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtsControllerTest.java
  src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtOpeningTimeServiceTest.java
  src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminServiceTest.java
  src/test/resources/opening-times.json
Labels: ns:fact, prd:fact, rel:fact-api-pr-284

#282 FACT-366 - Added new postcode search feature
  build.gradle
  src/main/java/uk/gov/hmcts/dts/fact/controllers/SearchController.java
  src/main/java/uk/gov/hmcts/dts/fact/services/CourtService.java
  src/main/java/uk/gov/hmcts/dts/fact/services/search/IProximitySearch.java
  src/main/java/uk/gov/hmcts/dts/fact/services/search/ProximitySearch.java
  src/test/java/uk/gov/hmcts/dts/fact/controllers/SearchControllerTest.java
  src/test/java/uk/gov/hmcts/dts/fact/search/ProximitySearchTest.java
  src/test/java/uk/gov/hmcts/dts/fact/services/CourtServiceTest.java
Labels: ns:fact, prd:fact, rel:fact-api-pr-282

#292 MapIt key-issue patch
  src/integrationTest/java/uk/gov/hmcts/dts/fact/mapit/MapitClientTest.java
  src/main/resources/db/migration/V085__batch_court_changes_7.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-292

#293 FACT-408 - Handle opening type in opening time table and add new admin endpoint for opening type
  src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtOpeningTimeEndpointTest.java
  src/functionalTest/java/uk/gov/hmcts/dts/fact/util/TestUtil.java
  src/integrationTest/java/uk/gov/hmcts/dts/fact/repositories/OpeningTypeRepositoryTest.java
  src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtOpeningTimesController.java
  src/main/java/uk/gov/hmcts/dts/fact/entity/OpeningTime.java
  src/main/java/uk/gov/hmcts/dts/fact/entity/OpeningType.java
  src/main/java/uk/gov/hmcts/dts/fact/model/admin/CourtGeneralInfo.java
  src/main/java/uk/gov/hmcts/dts/fact/model/admin/OpeningTime.java
  src/main/java/uk/gov/hmcts/dts/fact/model/admin/OpeningType.java
  src/main/java/uk/gov/hmcts/dts/fact/repositories/OpeningTypeRepository.java
  src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtOpeningTimeService.java
  src/main/resources/db/migration/V086__add_opening_type_to_opening_time_table.sql
  src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtOpeningTimesControllerTest.java
  src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtsControllerTest.java
  src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtOpeningTimeServiceTest.java
  src/test/java/uk/gov/hmcts/dts/fact/util/TestHelper.java
  src/test/resources/opening-times.json
  src/test/resources/opening-types.json
Labels: ns:fact, prd:fact, rel:fact-api-pr-293

#294 FACT-458 - Court batch changes 8
  src/main/resources/db/migration/V087__batch_court_changes_8.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-294

#298 FACT-474 - Tameside update 1
  src/main/resources/db/migration/V088__tameside_magistrates_court_alert_1.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-298

#300 FACT-478 - Tameside update 2
  src/main/resources/db/migration/V089__tameside_magistrates_court_alert_2.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-300

#296 FACT-408 - Fix issue with adding new opening times to courts with no existing opening times
  src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtGeneralInfoEndpointTest.java
  src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtOpeningTimeEndpointTest.java
  src/functionalTest/java/uk/gov/hmcts/dts/fact/util/TestUtil.java
  src/integrationTest/java/uk/gov/hmcts/dts/fact/repositories/OpeningTypeRepositoryTest.java
  src/integrationTest/resources/deprecated/aylesbury-magistrates-court-and-family-court.json
  src/main/java/uk/gov/hmcts/dts/fact/config/security/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtGeneralInfoController.java
  src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtOpeningTimesController.java
  src/main/java/uk/gov/hmcts/dts/fact/entity/OpeningTime.java
  src/main/java/uk/gov/hmcts/dts/fact/model/CourtForDownload.java
  src/main/java/uk/gov/hmcts/dts/fact/model/OpeningTime.java
  src/main/java/uk/gov/hmcts/dts/fact/model/admin/OpeningTime.java
  src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtOpeningTimeService.java
  src/main/resources/db/migration/V090__add_extra_court_opening_types.sql
  src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtGeneralInfoControllerTest.java
  src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtOpeningTimesControllerTest.java
  src/test/java/uk/gov/hmcts/dts/fact/services/CourtServiceTest.java
  src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtOpeningTimeServiceTest.java
Labels: ns:fact, prd:fact, rel:fact-api-pr-296

#301 FACT-479 - Remove default authentication provider URL, admin usernames and password for functional tests
  Jenkinsfile_CNP
  README.md
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/dts/fact/util/OAuthClient.java
Labels: ns:fact, prd:fact, rel:fact-api-pr-301

#307 FACT-445 - MapCourtCodeTests added
  src/test/java/uk/gov/hmcts/dts/fact/util/MapCourtCodeTest.java
Labels: ns:fact, prd:fact, rel:fact-api-pr-307
