Repository hmcts/fact-api, pull requests merged in 2021-06, with the labels that each got.

#348 FACT-70 - Minor update for comparing court types from admin portal
  src/main/java/uk/gov/hmcts/dts/fact/exception/GlobalControllerExceptionHandler.java
  src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtTypesService.java
  src/main/java/uk/gov/hmcts/dts/fact/util/CourtType.java
  src/main/java/uk/gov/hmcts/dts/fact/util/MapCourtCode.java
  src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtTypesControllerTest.java
  src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtTypeServiceTest.java
  src/test/java/uk/gov/hmcts/dts/fact/util/MapCourtCodeTest.java
Labels: ns:fact, prd:fact, rel:fact-api-pr-348

#349 FACT-562 - Fix issue with email/phone number/opening hour not displaying the right descriptions in the downloaded court list
  src/integrationTest/java/uk/gov/hmcts/dts/fact/repositories/ContactTypeRepositoryTest.java
  src/integrationTest/java/uk/gov/hmcts/dts/fact/repositories/OpeningTypeRepositoryTest.java
  src/main/java/uk/gov/hmcts/dts/fact/entity/Contact.java
  src/main/java/uk/gov/hmcts/dts/fact/entity/ContactType.java
  src/main/java/uk/gov/hmcts/dts/fact/entity/Element.java
  src/main/java/uk/gov/hmcts/dts/fact/entity/ElementType.java
  src/main/java/uk/gov/hmcts/dts/fact/entity/Email.java
  src/main/java/uk/gov/hmcts/dts/fact/entity/EmailType.java
  src/main/java/uk/gov/hmcts/dts/fact/entity/OpeningTime.java
  src/main/java/uk/gov/hmcts/dts/fact/entity/OpeningType.java
  src/main/java/uk/gov/hmcts/dts/fact/entity/util/ElementFormatter.java
  src/main/java/uk/gov/hmcts/dts/fact/model/Contact.java
  src/main/java/uk/gov/hmcts/dts/fact/model/CourtForDownload.java
  src/main/java/uk/gov/hmcts/dts/fact/model/Email.java
  src/main/java/uk/gov/hmcts/dts/fact/model/OpeningTime.java
  src/main/java/uk/gov/hmcts/dts/fact/model/admin/Contact.java
  src/main/java/uk/gov/hmcts/dts/fact/model/admin/ContactType.java
  src/main/java/uk/gov/hmcts/dts/fact/model/admin/Email.java
  src/main/java/uk/gov/hmcts/dts/fact/model/admin/OpeningTime.java
  src/main/java/uk/gov/hmcts/dts/fact/model/admin/OpeningType.java
  src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtContactService.java
  src/main/java/uk/gov/hmcts/dts/fact/util/Utils.java
  src/test/java/uk/gov/hmcts/dts/fact/entity/ContactTest.java
  src/test/java/uk/gov/hmcts/dts/fact/entity/EmailTest.java
  src/test/java/uk/gov/hmcts/dts/fact/entity/util/ElementFormatterTest.java
  src/test/java/uk/gov/hmcts/dts/fact/model/ContactTest.java
  src/test/java/uk/gov/hmcts/dts/fact/model/CourtForDownloadTest.java
  src/test/java/uk/gov/hmcts/dts/fact/model/CourtTest.java
  src/test/java/uk/gov/hmcts/dts/fact/model/OpeningTimeTest.java
  src/test/java/uk/gov/hmcts/dts/fact/model/admin/CourtTest.java
  src/test/java/uk/gov/hmcts/dts/fact/model/admin/EmailTest.java
  src/test/java/uk/gov/hmcts/dts/fact/services/CourtServiceTest.java
  src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtContactServiceTest.java
  src/test/java/uk/gov/hmcts/dts/fact/util/UtilsTest.java
Labels: ns:fact, prd:fact, rel:fact-api-pr-349

#350 FACT-562 Minor readme file update to restart failing build
  README.md
Labels: ns:fact, prd:fact, rel:fact-api-pr-350

#354 FACT-449 - Fix sonarqube complain on missing null check
  README.md
  src/main/java/uk/gov/hmcts/dts/fact/mapit/MapItService.java
Labels: ns:fact, prd:fact, rel:fact-api-pr-354

#356 FACT-586 - Court Batch Changes 14
  src/main/resources/db/migration/V106__batch_court_changes_14.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-356

#355 fixed updates are not reflecting properly on the fact front end by re…
  src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtTypesService.java
Labels: ns:fact, prd:fact, rel:fact-api-pr-355

#357 FACT-587 - Court batch changes 15
  src/main/resources/db/migration/V107__batch_court_changes_15.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-357

#359 CVE-2021-22118-Patch - Upgraded SpringBoot to 2.3.11.RELEASE
  build.gradle
Labels: ns:fact, prd:fact, rel:fact-api-pr-359

#366 Fact 594 - partial postcode functionality
  src/functionalTest/java/uk/gov/hmcts/dts/fact/ServiceEndpointTest.java
  src/integrationTest/java/uk/gov/hmcts/dts/fact/mapit/MapitClientTest.java
  src/main/java/uk/gov/hmcts/dts/fact/controllers/ServicesController.java
  src/main/java/uk/gov/hmcts/dts/fact/mapit/MapItHealthService.java
  src/main/java/uk/gov/hmcts/dts/fact/mapit/MapitClient.java
  src/main/java/uk/gov/hmcts/dts/fact/mapit/MapitHealthIndicator.java
  src/main/java/uk/gov/hmcts/dts/fact/services/MapitService.java
  src/main/java/uk/gov/hmcts/dts/fact/services/validation/PostcodeValidator.java
  src/main/java/uk/gov/hmcts/dts/fact/services/validation/ValidationService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/dts/fact/mapit/MapitHealthIndicatorTest.java
  src/test/java/uk/gov/hmcts/dts/fact/services/MapitServiceTest.java
  src/test/java/uk/gov/hmcts/dts/fact/services/validation/PostcodeValidatorTest.java
  src/test/java/uk/gov/hmcts/dts/fact/services/validation/ValidateServiceTest.java
Labels: ns:fact, prd:fact, rel:fact-api-pr-366

#367 FACT-631 - Court Batch Changes 16
  src/main/resources/db/migration/V108__batch_court_changes_16.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-367

#371 FACT-100 - Fix sonarqube issue complaints by adding more tests, and disable Mapit unit tests
  src/integrationTest/java/uk/gov/hmcts/dts/fact/mapit/MapitClientTest.java
  src/main/java/uk/gov/hmcts/dts/fact/mapit/MapItHealthService.java
  src/test/java/uk/gov/hmcts/dts/fact/entity/OpeningTimeTest.java
  src/test/java/uk/gov/hmcts/dts/fact/mapit/MapItHealthServiceTest.java
  src/test/java/uk/gov/hmcts/dts/fact/model/admin/OpeningTimeTest.java
  src/test/java/uk/gov/hmcts/dts/fact/services/validation/PostcodeValidatorTest.java
Labels: ns:fact, prd:fact, rel:fact-api-pr-371

#372 FACT-668 - Court Batch Changes 17
  src/main/resources/db/migration/V109__batch_court_changes_17.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-372

#373 FACT-573 - Add API endpoints to retrieve, add and delete postcodes for admin portal
  charts/fact-api/Chart.yaml
  src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtPostcodeEndpointTest.java
  src/functionalTest/java/uk/gov/hmcts/dts/fact/util/FunctionalTestBase.java
  src/integrationTest/java/uk/gov/hmcts/dts/fact/repositories/CourtPostcodeRepositoryTest.java
  src/integrationTest/java/uk/gov/hmcts/dts/fact/services/AdminCourtPostcodeServiceTest.java
  src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtAreasOfLawController.java
  src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtPostcodeController.java
  src/main/java/uk/gov/hmcts/dts/fact/entity/Court.java
  src/main/java/uk/gov/hmcts/dts/fact/entity/CourtLocalAuthorityAreaOfLaw.java
  src/main/java/uk/gov/hmcts/dts/fact/entity/CourtPostcode.java
  src/main/java/uk/gov/hmcts/dts/fact/exception/GlobalControllerExceptionHandler.java
  src/main/java/uk/gov/hmcts/dts/fact/exception/InvalidPostcodeException.java
  src/main/java/uk/gov/hmcts/dts/fact/exception/PostcodeExistedException.java
  src/main/java/uk/gov/hmcts/dts/fact/exception/PostcodeNotFoundException.java
  src/main/java/uk/gov/hmcts/dts/fact/repositories/CourtPostcodeRepository.java
  src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtPostcodeService.java
  src/main/java/uk/gov/hmcts/dts/fact/services/validation/PostcodeValidator.java
  src/main/java/uk/gov/hmcts/dts/fact/services/validation/ValidationService.java
  src/main/java/uk/gov/hmcts/dts/fact/util/PostcodeArea.java
  src/main/java/uk/gov/hmcts/dts/fact/util/Utils.java
  src/main/resources/ukPostcodeAreas.json
  src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtPostcodeControllerTest.java
  src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtPostcodeServiceTest.java
  src/test/java/uk/gov/hmcts/dts/fact/services/validation/PostcodeValidatorTest.java
  src/test/java/uk/gov/hmcts/dts/fact/services/validation/ValidateServiceTest.java
  src/test/java/uk/gov/hmcts/dts/fact/util/PostcodeAreaTest.java
  src/test/java/uk/gov/hmcts/dts/fact/util/UtilsTest.java
Labels: ns:fact, prd:fact, rel:fact-api-pr-373

#376 FACT-687 - Court Batch Changes 18
  src/main/resources/db/migration/V110__batch_court_changes_18.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-376

#377 Added CODEOWNERS
  .github/CODEOWNERS
Labels: ns:fact, prd:fact, rel:fact-api-pr-377
