Repository hmcts/fact-api, pull requests merged in 2022-04, with the labels that each got.

#620 address CVE-2022-21724
  build.gradle
Labels: ns:fact, prd:fact, rel:fact-api-pr-620

#622 updating dependencies
  build.gradle
Labels: ns:fact, prd:fact, rel:fact-api-pr-622

#628 address dependencies
  config/owasp/suppressions.xml
Labels: ns:fact, prd:fact, rel:fact-api-pr-628

#626 FACT-1150: Updating search_servicearea id column to auto-generate id
  src/main/resources/db/migration/V149__update_search_servicearea_id_column_update_court_lat_lon.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-626

#629 Fact 1150
  src/main/resources/db/migration/V150__add_service_area_to_service_centre.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-629

#631 Fact 1153
  src/main/resources/db/migration/V151__update_court_intro_char_limit.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-631

#632 address CVE-2016-1000027
  config/owasp/suppressions.xml
Labels: ns:fact, prd:fact, rel:fact-api-pr-632

#627 adding address description
  build.gradle
  config/owasp/suppressions.xml
  src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtAddressEndpointTest.java
  src/main/java/uk/gov/hmcts/dts/fact/entity/CourtAddress.java
  src/main/java/uk/gov/hmcts/dts/fact/model/CourtAddress.java
  src/main/java/uk/gov/hmcts/dts/fact/model/admin/CourtAddress.java
  src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtAddressService.java
  src/main/resources/db/migration/V152__add_address_description_for_court_address.sql
  src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtAddressControllerTest.java
  src/test/java/uk/gov/hmcts/dts/fact/model/admin/CourtAddressTest.java
  src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtAddressServiceTest.java
Labels: ns:fact, prd:fact, rel:fact-api-pr-627

#635 Fact 1153: Increasing char limited to account for html tags
  src/main/resources/db/migration/V153__update_court_intro_char_limit.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-635
