Repository hmcts/fact-api, pull requests merged in 2022-09, with the labels that each got.

#702 Fact 1015
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtFacilityEndpointTest.java
  src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/list/AdminContactTypeEndpointTest.java
  src/main/java/uk/gov/hmcts/dts/fact/entity/EmailType.java
  src/main/java/uk/gov/hmcts/dts/fact/repositories/EmailTypeRepository.java
  src/main/java/uk/gov/hmcts/dts/fact/services/admin/list/AdminContactTypeService.java
  src/main/resources/db/migration/V171__synchronise_contact_email_types.sql
  src/test/java/uk/gov/hmcts/dts/fact/services/admin/list/AdminContactTypeServiceTest.java
Labels: ns:fact, prd:fact, rel:fact-api-pr-702

#707 Fact 1242
  src/main/resources/db/migration/V172__update_court_urgent_message.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-707

#710 update springboot 2.7.3
  build.gradle
  config/owasp/suppressions.xml
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/uk/gov/hmcts/dts/fact/config/SwaggerConfiguration.java
  src/main/resources/application.yaml
Labels: ns:fact, prd:fact, rel:fact-api-pr-710

#704 adding fortify
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:fact, prd:fact, rel:fact-api-pr-704

#714 adding new migration to remove text
  src/main/resources/db/migration/V174__update_court_urgent_message.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-714
