Repository hmcts/fact-api, pull requests merged in 2023-06, with the labels that each got.

#767 DTSPO-13810 reschedule nightlybuilds to start at 8am
  Jenkinsfile_nightly
Labels: ns:fact, prd:fact, rel:fact-api-pr-767

#769 Edinburgh Social Security and Child Support Tribunal Lat Long update
  src/main/resources/db/migration/V192__update_edinburgh_long_lat.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-769

#771 Redone Lat Long changes for Edinburgh Social Security and Child Support Tribunal
  build.gradle
  config/owasp/suppressions.xml
  src/main/resources/db/migration/V193__update_edinburgh_long_lat_again.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-771
