Repository hmcts/fact-api, pull requests merged in 2023-05, with the labels that each got.

#760 changing version
  build.gradle
  charts/fact-api/Chart.yaml
  config/owasp/suppressions.xml
Labels: ns:fact, prd:fact, rel:fact-api-pr-760

#762 update to remove orphans from db table
  build.gradle
  src/main/resources/db/migration/V191__remove_orphan_application_updates.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-762

#763 resolve CVE-2018-1258
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:fact, prd:fact, rel:fact-api-pr-763
