Repository hmcts/fact-api, pull requests merged in 2023-11, with the labels that each got.

#783 add general enquiry form to all active courts
  src/main/resources/db/migration/V198__add_general_ form_link_ to_ all_ courts.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-783

#786 FACT-1536 fixing db connection
  charts/fact-api/Chart.yaml
  charts/fact-api/values.yaml
Labels: ns:fact, prd:fact, rel:fact-api-pr-786

#787 Fix DB name in secrets and change values to flex
  charts/fact-api/Chart.yaml
  charts/fact-api/values.yaml
  infrastructure/main.tf
Labels: ns:fact, prd:fact, add-or-update, rel:fact-api-pr-787

#784 close south west regional divorce centre
  src/main/resources/db/migration/V199__close_south_west_regional_divorce_centre.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-784

#788 remove ss, change secret values
  infrastructure/main.tf
  infrastructure/tf-db-flexible-secrets.tf
Labels: ns:fact, prd:fact, destroy, rel:fact-api-pr-788

#790 changing to non flex sn
  charts/fact-api/Chart.yaml
  charts/fact-api/values.yaml
Labels: ns:fact, prd:fact, rel:fact-api-pr-790

#791 update bury st edmunds divorce centre
  src/main/resources/db/migration/V200__update_bury_st_edmunds_divorce_centre.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-791
