Repository hmcts/fact-api, pull requests merged in 2024-09, with the labels that each got.

#826 FACT-1947 CVEs
  build.gradle
Labels: ns:fact, prd:fact, rel:fact-api-pr-826

#827 FACT-1962 added Court of Protection option
  src/main/resources/db/migration/V205__add_court_of_protection_email_type.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-827

#829 FACT-1951 add Scotland region and associated courts
  src/main/resources/db/migration/V207__add_new_region_scotland_and_update_courts.sql
Labels: ns:fact, prd:fact, rel:fact-api-pr-829

#830 Fixed vuln
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:fact, prd:fact, rel:fact-api-pr-830
