Repository hmcts/fact-api, pull requests merged in 2024-06, with the labels that each got.

#813 Fix master
  infrastructure/state.tf
Labels: ns:fact, prd:fact, aat/add-or-update, prod/add-or-update, rel:fact-api-pr-813

#814 FACT-1792 - open API
  .github/workflows/publish-openapi.yaml
  .github/workflows/swagger.yaml
  src/main/resources/application.yaml
Labels: ns:fact, prd:fact, rel:fact-api-pr-814

#816 FACT-1675 update readme for fact-api
  README.md
Labels: ns:fact, prd:fact, rel:fact-api-pr-816

#815 FACT-1500 - Court Name History
  src/functionalTest/java/uk/gov/hmcts/dts/fact/CourtsEndpointTest.java
  src/functionalTest/java/uk/gov/hmcts/dts/fact/admin/AdminCourtHistoryEndpointTest.java
  src/integrationTest/java/uk/gov/hmcts/dts/fact/repositories/CourtHistoryRepositoryTest.java
  src/integrationTest/java/uk/gov/hmcts/dts/fact/repositories/CourtRepositoryTest.java
  src/main/java/uk/gov/hmcts/dts/fact/controllers/CourtsController.java
  src/main/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtHistoryController.java
  src/main/java/uk/gov/hmcts/dts/fact/entity/CourtHistory.java
  src/main/java/uk/gov/hmcts/dts/fact/model/CourtReferenceWithHistoricalName.java
  src/main/java/uk/gov/hmcts/dts/fact/model/admin/CourtHistory.java
  src/main/java/uk/gov/hmcts/dts/fact/repositories/CourtHistoryRepository.java
  src/main/java/uk/gov/hmcts/dts/fact/repositories/CourtRepository.java
  src/main/java/uk/gov/hmcts/dts/fact/services/CourtService.java
  src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtHistoryService.java
  src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminService.java
  src/main/java/uk/gov/hmcts/dts/fact/util/AuditType.java
  src/main/resources/db/migration/V203__add_admin_court_history_table.sql
  src/main/resources/db/migration/V204__add_admintype_entries_for_court_history.sql
  src/test/java/uk/gov/hmcts/dts/fact/controllers/CourtsControllerTest.java
  src/test/java/uk/gov/hmcts/dts/fact/controllers/admin/AdminCourtHistoryControllerTest.java
  src/test/java/uk/gov/hmcts/dts/fact/services/CourtServiceTest.java
  src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminCourtHistoryServiceTest.java
  src/test/java/uk/gov/hmcts/dts/fact/services/admin/AdminServiceTest.java
Labels: ns:fact, prd:fact, rel:fact-api-pr-815

#812 update to j 21
  Dockerfile
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:fact, prd:fact, rel:fact-api-pr-812

#817 fix code smell
  src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminService.java
Labels: ns:fact, prd:fact, rel:fact-api-pr-817

#818 Code smells
  src/main/java/uk/gov/hmcts/dts/fact/services/admin/AdminService.java
Labels: ns:fact, prd:fact, rel:fact-api-pr-818

#819 cve updates
  build.gradle
Labels: ns:fact, prd:fact, rel:fact-api-pr-819

#821 remove properties-volume-spring-boot-starter
  build.gradle
Labels: ns:fact, prd:fact, rel:fact-api-pr-821
