Repository hmcts/fact-api, pull requests merged in 2025-06, with the labels that each got.

#856 FACT-2394 Move to Azure
  build.gradle
Labels: ns:fact, prd:fact, rel:fact-api-pr-856

#857 FACT-2407 Monthly updates
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: ns:fact, prd:fact, rel:fact-api-pr-857

#859 FACT-2446 added fix for TransientObjectException error
  src/main/java/uk/gov/hmcts/dts/fact/entity/CourtAddress.java
  src/main/java/uk/gov/hmcts/dts/fact/entity/CourtSecondaryAddressType.java
Labels: ns:fact, prd:fact, rel:fact-api-pr-859
