Repository hmcts/fact-api, pull requests merged in 2025-07, with the labels that each got.

#860 FACT-2429 automerge
  .github/dependabot.yml
  .github/renovate.json
Labels: ns:fact, prd:fact, rel:fact-api-pr-860

#862 removed other renovate
  renovate.json
Labels: ns:fact, prd:fact, rel:fact-api-pr-862

#866 Delete .github/CODEOWNERS
  .github/CODEOWNERS
Labels: ns:fact, prd:fact, rel:fact-api-pr-866
